name: Deploy to Databricks (dev)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      # Secretsを環境変数に流し込む
      - name: Configure Auth
        run: |
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV
          echo "DAB_VAR_dev_host=${{ secrets.DATABRICKS_HOST_DEV }}" >> $GITHUB_ENV

      - name: Validate bundle
        run: databricks bundle validate

      - name: Preview
        run: databricks bundle summarize --target "${TARGET}"

      - name: Deploy
        run: databricks bundle deploy --target "${TARGET}"
